### ISSUE TITLE
Project Plan

### ISSUE THREAD

**Issue by DavidVasilev1** [CSA-Tri-1/projectTri1#5]
# Project Planning
> Creating a timeline and checkpoints for Dijkstra project.

[Video](https://youtu.be/erzel9eYmGA)

**Description:** 

Our goal is to create a website that is shows an implementation of machine learning, in this case pathfinding. We will be using the Dijkstra algorithm to path-find through a user created map. This will help demonstrate our version of this algorithm, as well as potentially implement a game version of this algorithm where the user compares their version of a path to the computer calculated one. We will also have a page that describes this algorithm and the tools we used to make it work.

## Frontend
> Create clean, simple design, containing an editable map for the Dijkstra algorithm. Having an About and Game page as well with leaderboards and simple descriptions.

This will be everything the user sees and interacts with, including the home, app, game, leaderboard, log-in, and about page.

### Homepage
> Contain main information on the App and Game with brief descriptions.

- [x] Navbar with links to all pages, containing logo
- [x] Frontpage with name of algorithm with definition (simple)
- [ ] Section summarizing app element of site
- [ ] Section summarizing game element of site

![Image](https://github.com/CSA-Tri-1/DADDiJkstra/assets/111480448/c2174725-f1cd-4a77-92f3-26ea9fcfd9b9)

### App Page
> Create editable canvas that guides user through creating node graph and running Dijkstra.

- [ ] Navbar with links to all pages, containing logo
- [ ] Panel showing instruction on how to use canvas
- [x] Canvas with ability to place, remove, and link nodes to run Dijkstra on
  - [x] Joint JS - creates editable canvas for node and path placement
  - [x] Calculate distances of paths to 
  - [x] package data into JSON and send to backend
  - [ ] fetch path from backend algorithm and display for user

![Image](https://github.com/CSA-Tri-1/DADDiJkstra/assets/111480448/f68ae44b-a40e-4c68-b59d-f576512a42a8)

### Game Page (tentative)
> Create generated graph with clickable paths and pre-defined start and end nodes.

- [x] Generate graph with nodes and paths
- [ ] Selectable paths for the user to select and submit their guess
  - [ ] Pull data from the backend on the path and display on frontend
  - [ ] Comparison between actual path and user path to calculate score
- [ ] Have leaderboard that shows the score and the score of other users
- [ ] Login to have separate users

![Image](https://github.com/CSA-Tri-1/DADDiJkstra/assets/111480448/56121abc-67b1-448d-bdfe-f6d9dc299ef5)

#### Login Page (tentative)
> Generic login page for users to document their scores from the game element

- [x] Have login page, generic
- [ ] Sending data to backend for registration and pulling data from backend to log user scores
Optional:
- [ ] JWT or Firebase

#### Leaderboard Page (tentative)
> Display all data from the users, including score and name

- [ ] Pull data from backend, displaying data with jQuery

### About Page
> Show major information on Dijkstra in an interactive way

- [x] Have frontpage, showing the topic of the page
- [ ] Split into 5 main sections:
  - [ ] The Algorithm - what is it
  - [ ] How it Works - nodes and weighted paths
  - [ ] Frontend - JointJS, Svelte and Windtail, DaisyUI
  - [ ] Backend - Code, Database, JSON connections
  - [ ] Summary/Conclusion - main concepts (Java, API, JointJS, Svelte and Windtail, DaisyUI)
- [ ] Include sections of code, images, animations

![Image](https://github.com/CSA-Tri-1/DADDiJkstra/assets/111480448/23af91ef-6e03-4398-aea5-734504a8ff8e)

## Backend
> Store data and complete algorithm in this space

This is where all of the processing and storage happens for the leaderboard and machine learning algorithm.

### Dijkstra
> Path finding algorithm, taking data of nodes and paths from frontend, calculating, and sending path to frontend

- [ ] Class based structure, have nodes (contain connected nodes and paths) and paths (contain weights and connected nodes)
- [ ] Pick first node, compare all path weights and go along that path to the next node
  - [ ] Do this until finish is reached
  - [ ] Output JSON of node, path pairs until the last node
  - [ ] Send to frontend to display

![image](https://github.com/CSA-Tri-1/DADDiJkstra/assets/111480448/2bfdd2a5-2003-44c0-b4ac-9a41034298be)

### Leaderboard
> Store data from game users and send JSON data to frontend for leaderboard

- [ ] Database file with name, password, top score
  - [ ] Simple database like before
  - [ ] Receive and send data to frontend via JSON

### Deployment
> DevOps will deploy the backend

- [ ] Use AWS to deploy project with a static global link

### Collaboration 
> Group meetings 

- In order to show collaboration as well as keeping track of how far the product has come along so far we will be adopting meetings each week in which we review what new things have been added as well as any new ideas
- Each meeting will consist of a ticket summarizing what was talked about
- Outside of these meetings, we will be providing aid and helping each other out with different issues and providing different perspectives 
- We will also dicuss things at the start of the week regarding the plans for the week and this will help us coordinate what we are doing
